version: "3.3"

services:
    
  frontend:
    image: martonbod/coster.io-frontend:latest
    container_name: coster-frontend
    restart: on-failure    
    ports:
      - "3000:3000"

  expense-svc:
    image: martonbod/coster.io-expense-svc:latest
    container_name: coster-expense-svc 
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5050,server=y,suspend=n
    volumes:
      - ./logs:/logs

  dashboard-svc:
    image: martonbod/coster.io-dashboard-svc:latest
    container_name: coster-dashboard-svc 
    restart: on-failure
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5051,server=y,suspend=n
    volumes:
      - ./logs:/logs

  user-mgmt-svc:
    image: martonbod/coster.io-user-mgmt-svc:latest
    container_name: coster-user-mgmt-svc
    restart: on-failure
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5052,server=y,suspend=n
    volumes:
      - ./logs:/logs

  notification-svc:
    image: martonbod/coster.io-notification-svc:latest
    container_name: coster-notification-svc
    restart: on-failure
    ports:
      - "9003:9003"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5053,server=y,suspend=n
    volumes:
      - ./logs:/logs

  postgres:
    image: postgres:latest
    container_name: coster-postgres
    restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=coster


