version: "3.3"

services:
  expense-svc:
    image: coster.io/expense-svc
    container_name: expense-svc 
    ports:
      - "9000:8080"
    environment:
      - USER_SERVICE_HOST=user-mgmt-svc
      - USER_SERVICE_PORT=8080
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5050,server=y,suspend=n

  dashboard-svc:
    image: coster.io/dashboard-svc
    container_name: dashboard-svc 
    ports:
      - "9002:8080"
    environment:
      - USER_SERVICE_HOST=user-mgmt-svc
      - USER_SERVICE_PORT=8080
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5050,server=y,suspend=n  

  user-mgmt-svc:
    image: coster.io/user-mgmt-svc
    container_name: user-mgmt-svc
    ports:
      - "9001:8080"
    environment:
      - JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,address=*:5051,server=y,suspend=n
